# Generated by Django 5.2.10 on 2026-01-27 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя клииента')),
                ('chat_id', models.CharField(max_length=64, verbose_name='ID пользователя')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Тип заказа')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новый ли клиент')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('name', models.CharField(max_length=64, verbose_name='Имя клиента')),
                ('visit_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата визита мастера')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Выполнен ли заказ')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.user', verbose_name='Пользователь')),
            ],
        ),
    ]
